### PR TITLE
This should fix the disappearing of the text when enter a break line …

### PR DESCRIPTION
**Pull request by ShamsaHamed**
…before a space.

With this code any linebreak should only break the line without add a dropcap unless
you remove the space, the dropcaps will be applied to next character

### CODE REVIEW

**Comment by Fahad-Alsaidi** [comment]
This bug is in upstream [13871](https://bugs.scribus.net/view.php?id=13871)

**Comment by khaledhosny** [comment]
I don’t understand this fix, what changed here compared to the old code?

**Comment by ShamsaHamed** [comment]
It check that if the current character is a blank it will not be drop cap,
only newline will be applied. May be it isn't the reasonable solution but
at least it prevents the bug.

**Comment by khaledhosny** [comment]
@Fahad-Alsaidi can you check if this issue is fixed now?

**Comment by Fahad-Alsaidi** [comment]
Yes, it is fixed.

**Pull request closed without merging**
