### PR TITLE
Add Font Features into Style Manager

### PR DESCRIPTION
**Pull request by Fahad-Alsaidi**
in addition, I organized the Font Features setting to be compact and easy to navigate. Part of #190.

### CODE REVIEW

**Comment by khaledhosny** [comment]
Looks fine, but I don’t like the “click to select” thing for stylistic set, doing it like it is done in the properties pallette would be better IMO (in the future when #192 is implemented, the number of sets presented will be usually small as we will only show what is present in the font). Also I’d prefer that Capitals and Positions be done as a label and a group like Ligatures and Numerals so that things look consistent, and drop the colon after the labels.

**Comment by Fahad-Alsaidi** [comment]
I did some search how other DTPs presenting OpenType Feature. Have a look to this screen-shot:
20070725_fg03
_The above screen shots show how QuarkXPress (top) and InDesign (bottom) handle OpenType features in paragraph style sheets_
Current implementation for OpenType feature in PropertyWidget_FontFeatures takes a lot of space and redundant. It is very long that you need to scroll down many times to see all setting.
My implementation is more user friendly and elegant. 
scribus-opentypeff

Your feedback are welcomed: @aoloe @luzpaz  @MrB74 

I will update the patch to  drop the colon after the labels soon.

**Comment by MrB74** [comment]
I think this looks good! Nice work!

The colons are fine and standard

Craig

**Comment by khaledhosny** [comment]
I’m commenting about the inconsistency here, ligatures and numerals has a frame, the others don’t. This looks ugly, either all of them be framed or all don’t.

And the click to select thing is just plain ugly, I never have seen a UI like this.

70afcfec-2728-11e6-93a8-6060bb54e505

**Comment by MrB74** [comment]
So a group box needs to be found for the two in the middle.. 

Or separate the groups with horizontal lines if required.

My judgement is out on the stylistic sets thing until I see what that is for. You’re right, it can be better. 

Craig

**Comment by Fahad-Alsaidi** [comment]
The group box meant to group thing that have some thing common and this apply only for ligatures and Numerals setting. So this is something logical. 

> And the click to select thing is just plain ugly, I never have seen a UI like this.

Are you sure?? However, this depend on how you are familiar with other DTPs. See how MS Office for mac (though I think it only supports  one set):

Adobe Indesign:
in-opentypeff1
Now compare it with current implementation in PP:
sc-opentypeff2
Even if we fixed #192, we will just disable the sets not remove them in Style Manager because styles saved in SLA and I think it is a bad idea to modify  them without a user permission. I will discuss this later on in #192.

IMHO, It is a smart way to save space and keep things easy to grab.

**Comment by aoloe** [comment]
i basically agree with khaled... that was also my first impression.

if you cannot find a section for the three middle options, you can put them on top... that would look less strange.
but, if you have sections, it would indeed be better to put everything in sections... if possible.

and, for the stylistic sets, i guess that a drop down might be enough...

**Comment by Fahad-Alsaidi** [comment]
OK, Here how now  looks Font Features 
sc-opentypv2

**Comment by khaledhosny** [comment]
The PP stylistic sets look bad in Qt Designer, they look fine in the actual UI:


The “click to select text” is ugly, period. Removing the text makes it very undiscoverable, like InDesign (which is often criticised for its bad font features UI, not a great example). MS Oddice is even worse, since you can’t select more than one SS there which is plain wrong.

**Comment by khaledhosny** [comment]
I’d rather kill all the groups altogether since thy are just arbitrary, and use a flat structure with line between the sections like we do in the PP right now.

**Comment by Fahad-Alsaidi** [comment]
updated to fix last conflict.

> I’d rather kill all the groups altogether since thy are just arbitrary, and use a flat structure with line between the sections like we do in the PP right now.

Even though they are arbitrary, they provide help for newcomers who are not familiar with Open Type Features. Plus, if I remove it the whole design will be uglier. 
For stylistic sets, if you come up with a new idea rather then listing 20 check-boxs, I am willing to implement it.

**Comment by aoloe** [comment]
eh eh, nice things might be nice... but in design they'd better also fit a purpose...

personally, i tried to read a bit about the 20 stylistic sets but could not figure out what they're purpose here... and how to figure out what 1..20 means...
can anybody provide a business abstract? : - )

**Comment by zayedalsaidi** [comment]
@aoloe please see [this](https://www.microsoft.com/typography/otspec/features_pt.htm#ssxx) from OpenType specifications

**Comment by aoloe** [comment]
thanks @zayedalsaidi ! that document is much clearer than what i've found by googling!

**Comment by zayedalsaidi** [comment]
What about a button witch will open a dialog box like this? 

ss1

**Comment by aoloe** [comment]
i don't think providing a preview will be easy...
as far as i understood most sets apply only to specific letters and the meaning of the set changes from font to font.

my current personal preference on the set is:
- show the font specific label for each set (instead of the number);
- as (iirc) khaled previouslay said, only show the sets that are defined for the current font;
- use a selector inspired by the one used in this same issue tracker for labelling the issues  
  (a list of active choices is directly shown and you can activate (and maybe in our case also deactivate... to make things simpler) each option in a multiple choice drop down)

```
Curved punctuation, Flat terminals, Alternate capitals
[Add sets...           | v ]
---------------------------
|✓ Curved punctuation      |
|✓ Flat terminals          |
|✓ Alternate capitals      |
|  Simplfied Roman Low…    |
|  Two-Storey Italics      |
---------------------------
```

**Pull request merged**
